/**
 * Tests against the committed .kmz binaries in tests/fixtures.
 *
 * Distinct from parse.test.ts, which builds its archives in memory. Those tests
 * check the parser's logic; these check it against real ZIP files that went
 * through a real writer and are read back off disk — the path an actual upload
 * takes. A parser can pass every in-memory test and still fail on a file whose
 * entries are ordered differently or whose compression differs.
 *
 * The fixtures are generated by scripts/build-kmz-fixtures.mjs, where every
 * name and coordinate is invented. No real surveyed boundary is in this repo.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';
import type { GeometryCollection, Polygon, Position } from 'geojson';

import { INDIA_BOUNDS, parseKmz } from '../parse';
import { pointInRing, testDomParser } from './fixture';

const opts = { domParser: testDomParser };

const fixture = (name: string): Blob =>
  new Blob([readFileSync(resolve(process.cwd(), 'tests', 'fixtures', name))]);

const PARCELS = 'synthetic-parcels.kmz';
const CRESCENT = 'synthetic-crescent.kmz';
const SWAPPED = 'synthetic-swapped.kmz';

describe('root document discovery, against a real archive', () => {
  it('contains a decoy doc.kml, so this test can fail', async () => {
    // Without the decoy, a name-based lookup and a spec-based one would agree
    // and the assertion below would prove nothing.
    const zip = await JSZip.loadAsync(await fixture(PARCELS).arrayBuffer());
    const names = Object.keys(zip.files);

    expect(names).toContain('files/doc.kml');
    expect(names).toContain('parcels-survey-2026.kml');
    expect(names.filter((n) => n.toLowerCase().endsWith('.kml'))).toHaveLength(2);
  });

  it('reads the root .kml by position, not the nested one named doc.kml', async () => {
    const result = await parseKmz(fixture(PARCELS), PARCELS, opts);

    expect(result.kmlEntryName).toBe('parcels-survey-2026.kml');
    expect(result.kmlEntryName).not.toBe('files/doc.kml');
  });

  it('proves the decoy was not read, by where the geometry landed', async () => {
    // The decoy holds coordinates in Brazil. Had it been chosen, the bounds
    // check would have rejected the file instead of parsing it — so a passing
    // status is itself evidence about which document was used.
    const result = await parseKmz(fixture(PARCELS), PARCELS, opts);

    expect(result.status).toBe('parsed');
    const point = result.centroid as { lat: number; lng: number };
    expect(point.lng).toBeGreaterThanOrEqual(INDIA_BOUNDS.minLng);
    expect(point.lng).toBeLessThanOrEqual(INDIA_BOUNDS.maxLng);
  });
});

describe('geometry types', () => {
  it('parses all five placemarks', async () => {
    const result = await parseKmz(fixture(PARCELS), PARCELS, opts);
    expect(result.status).toBe('parsed');
    expect(result.placemarkCount).toBe(5);
  });

  it('yields each KML geometry as its GeoJSON counterpart', async () => {
    const { geometry } = await parseKmz(fixture(PARCELS), PARCELS, opts);

    // Several placemarks collapse into a GeometryCollection — see collectGeometry.
    expect(geometry?.type).toBe('GeometryCollection');
    const members = (geometry as GeometryCollection).geometries;
    expect(members).toHaveLength(5);

    const [simple, holed, multi, point, crescent] = members;

    expect(simple?.type).toBe('Polygon');
    expect((simple as Polygon).coordinates).toHaveLength(1);

    // The hole survives as a second linear ring. Dropping it would silently
    // enlarge the parcel by whatever the excluded area is.
    expect(holed?.type).toBe('Polygon');
    expect((holed as Polygon).coordinates).toHaveLength(2);

    // A MultiGeometry of two disjoint plots stays two, not one merged shape.
    expect(multi?.type).toBe('GeometryCollection');
    expect((multi as GeometryCollection).geometries.map((g) => g.type)).toEqual([
      'Polygon',
      'Polygon',
    ]);

    // A marker peg is valid: the rule is a Placemark with geometry, not a polygon.
    expect(point?.type).toBe('Point');

    expect(crescent?.type).toBe('Polygon');
  });
});

describe('representative point on a concave parcel', () => {
  it('returns a point inside the crescent, where a centroid would fall outside', async () => {
    const result = await parseKmz(fixture(CRESCENT), CRESCENT, opts);

    expect(result.status).toBe('parsed');
    expect(result.geometry?.type).toBe('Polygon');

    // The ring comes from the PARSED geometry rather than a copy of the
    // fixture's numbers, so the assertion is about the polygon the app actually
    // holds — not about what the generator was supposed to have written.
    const ring = ((result.geometry as Polygon).coordinates[0] as Position[]).map(
      ([lng, lat]) => [lng as number, lat as number] as const,
    );

    const point = result.centroid as { lat: number; lng: number };
    expect(pointInRing([point.lng, point.lat], ring)).toBe(true);

    // Guard the guard. If the vertex mean were inside this shape, the assertion
    // above would pass for a centroid implementation too and prove nothing —
    // this is what makes the fixture a crescent rather than decoration.
    const meanLng = ring.reduce((sum, [lng]) => sum + lng, 0) / ring.length;
    const meanLat = ring.reduce((sum, [, lat]) => sum + lat, 0) / ring.length;
    expect(pointInRing([meanLng, meanLat], ring)).toBe(false);
  });
});

describe('the transposed file', () => {
  it('is rejected, and not for a generic reason', async () => {
    const result = await parseKmz(fixture(SWAPPED), SWAPPED, opts);

    expect(result.status).toBe('unparseable');
    expect(result.centroid).toBeNull();
    expect(result.suspectedCoordinateSwap).toBe(true);
  });

  it('names the transposition and offers the fix', async () => {
    const result = await parseKmz(fixture(SWAPPED), SWAPPED, opts);
    const warning = result.warnings.find((w) => w.code === 'coordinates-out-of-range');

    expect(warning).toBeDefined();
    expect(warning?.message).toMatch(/transposed/i);
    expect(warning?.message).toMatch(/longitude first/i);
    expect(warning?.message).toMatch(/swap toggle/i);

    // The specific message, not the one used for a file that is genuinely
    // somewhere else. Telling a surveyor their file "covers the wrong area"
    // when the axes are reversed sends them to re-survey a correct parcel.
    expect(warning?.message).not.toMatch(/not a simple/i);
  });

  it('parses once the swap is applied, landing inside India', async () => {
    const result = await parseKmz(fixture(SWAPPED), SWAPPED, {
      ...opts,
      swapCoordinates: true,
    });

    expect(result.status).toBe('parsed');
    const point = result.centroid as { lat: number; lng: number };
    expect(point.lat).toBeGreaterThanOrEqual(INDIA_BOUNDS.minLat);
    expect(point.lat).toBeLessThanOrEqual(INDIA_BOUNDS.maxLat);
    expect(point.lng).toBeGreaterThanOrEqual(INDIA_BOUNDS.minLng);
    expect(point.lng).toBeLessThanOrEqual(INDIA_BOUNDS.maxLng);
  });
});

describe('the fixtures themselves', () => {
  it('holds only invented coordinates, all inside the India bounds', async () => {
    // A standing check on the repository, not on the parser. If someone ever
    // replaces a fixture with a real export, its coordinates will almost
    // certainly still be in India and this will not catch it — but a file from
    // anywhere else, or a placeholder, fails here rather than in review.
    for (const name of [PARCELS, CRESCENT]) {
      const { status, centroid } = await parseKmz(fixture(name), name, opts);
      expect(status).toBe('parsed');
      const point = centroid as { lat: number; lng: number };
      expect(point.lat).toBeGreaterThanOrEqual(INDIA_BOUNDS.minLat);
      expect(point.lat).toBeLessThanOrEqual(INDIA_BOUNDS.maxLat);
    }
  });
});
